python練習用ソースその2の追加
Tanpatsu/test pull request #5
Opened 2020-09-15 17:24 UTC by Tanpatsu

### 内容
- practice2.pyを新規作成

### 目的
- 2020/9/15の勉強内容を成果物として残すため

### レビュー観点
- 実装におかしなところはないか
- 文法、作法でおかしなところはないか

### 備考
- http://python.rdy.jp/wiki.cgi?page=FrontPage の「問題集」ページをもとに実施

2020-09-16 18:16 UTC, esperantoimo requested changes
修正をお願いします。

また、改行が2行の場所と１行の場所は何かポリシーがありますか？
意味のない改行が多くコードが見づらいので意味のある塊で改行を入れていください。

2020-09-16 18:16 UTC, esperantoimo commented on practice2.py
> +def gcd(a, b):  # 再帰関数
関数`gcb`の名称はどういう意味ですか？

2020-09-16 18:16 UTC, esperantoimo commented on practice2.py
> +s = 0
変数名には意味がある名称を付けてください

2020-09-16 18:16 UTC, esperantoimo commented on practice2.py
> +for x in list(range(1, 51)):
変数`x`も同様です。

2020-09-16 18:16 UTC, esperantoimo commented on practice2.py
> +        return gcd(b, a % b)
onelinerで記載してください

2020-09-16 18:16 UTC, esperantoimo commented on practice2.py
> +a, b = int(a), int(b)  # 入力値を数値型に変換
可読性が下がるので1つの変数でキャスト、再キャストを繰り返すのではなく変数を分けてください。

2020-09-16 23:32 UTC, Tanpatsu commented on practice2.py
> +def gcd(a, b):  # 再帰関数
最大公約数の英訳(greatest common divisor)が由来です。

2020-09-17 06:01 UTC, esperantoimo commented on practice2.py
> +def gcd(a, b):  # 再帰関数
略すと意味がわからなくなるので略さないでください。

2020-09-24 16:17 UTC, Tanpatsu commented on practice2.py
> +s = 0
変数名をsumに変更しました。

2020-09-24 16:17 UTC, Tanpatsu commented on practice2.py
> +        return gcd(b, a % b)
記述を修正しました。

2020-09-24 16:25 UTC, esperantoimo approved these changes
LGTM

2020-09-24 16:25 UTC, merged